-- MySQL Script generated by MySQL Workbench
-- Wed Jun 15 13:45:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartfinds
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartfinds` ;

-- -----------------------------------------------------
-- Schema smartfinds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartfinds` DEFAULT CHARACTER SET utf8 ;
USE `smartfinds` ;

-- -----------------------------------------------------
-- Table `smartfinds`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartfinds`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `displayName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pw` VARCHAR(45) NOT NULL,
  `userImgUrl` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartfinds`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartfinds`.`product` (
  `productid` INT NOT NULL AUTO_INCREMENT,
  `ownerid` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `imageUrl1` VARCHAR(200) NULL,
  `imageUrl2` VARCHAR(200) NULL,
  `imageUrl3` VARCHAR(200) NULL,
  `defaultPic` INT NULL,
  `price` DECIMAL(2) NOT NULL,
  `dateUpdated` DATETIME NOT NULL,
  `soldStatus` TINYINT NULL,
  `deleteStatus` TINYINT NULL,
  PRIMARY KEY (`productid`),
  CONSTRAINT `fk_product_user`
    FOREIGN KEY ()
    REFERENCES `smartfinds`.`user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartfinds`.`watchlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartfinds`.`watchlist` (
  `watchlistid` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `productid` INT NOT NULL,
  `dateUpdated` DATETIME NOT NULL,
  `deleteStatus` TINYINT NULL,
  `watchlist` VARCHAR(45) NULL,
  PRIMARY KEY (`watchlistid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartfinds`.`msginbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartfinds`.`msginbox` (
  `msginboxid` INT NOT NULL,
  `msgInboxUid` INT NOT NULL,
  `msgFromUid` INT NOT NULL,
  `msgToUid` INT NOT NULL,
  `msgLine` VARCHAR(1000) NOT NULL,
  `msgTimestamp` DATETIME NOT NULL,
  `msgProductId` INT NOT NULL,
  `user_userid` INT NOT NULL,
  PRIMARY KEY (`msginboxid`),
  INDEX `fk_msginbox_user1_idx` (`user_userid` ASC) VISIBLE,
  CONSTRAINT `fk_msginbox_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `smartfinds`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartfinds`.`msgdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartfinds`.`msgdetail` (
  `msgdetailid` INT NOT NULL,
  `msgInboxId` INT NOT NULL,
  `msgInboxUid` INT NOT NULL,
  `msgFromUid` INT NOT NULL,
  `msgToUid` INT NOT NULL,
  `msgTimestamp` DATETIME NOT NULL,
  `msginbox_msginboxid` INT NOT NULL,
  PRIMARY KEY (`msgdetailid`, `msginbox_msginboxid`),
  INDEX `fk_msgdetail_msginbox1_idx` (`msginbox_msginboxid` ASC) VISIBLE,
  CONSTRAINT `fk_msgdetail_msginbox1`
    FOREIGN KEY (`msginbox_msginboxid`)
    REFERENCES `smartfinds`.`msginbox` (`msginboxid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartfinds`.`watchlist_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smartfinds`.`watchlist_has_product` (
  `watchlist_watchlistid` INT NOT NULL,
  `product_productid` INT NOT NULL,
  `product_user_userid` INT NOT NULL,
  PRIMARY KEY (`watchlist_watchlistid`, `product_productid`, `product_user_userid`),
  INDEX `fk_watchlist_has_product_product1_idx` (`product_productid` ASC, `product_user_userid` ASC) VISIBLE,
  INDEX `fk_watchlist_has_product_watchlist1_idx` (`watchlist_watchlistid` ASC) VISIBLE,
  CONSTRAINT `fk_watchlist_has_product_watchlist1`
    FOREIGN KEY (`watchlist_watchlistid`)
    REFERENCES `smartfinds`.`watchlist` (`watchlistid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watchlist_has_product_product1`
    FOREIGN KEY (`product_productid`)
    REFERENCES `smartfinds`.`product` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
