-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 16:33:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CourseService
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CourseService
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CourseService` DEFAULT CHARACTER SET utf8 ;
USE `CourseService` ;

-- -----------------------------------------------------
-- Table `CourseService`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`Country` (
  `idCountry` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `countryCode` VARCHAR(45) NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`Course` (
  `idCourseCode` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `credit` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCourseCode`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`Course_Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`Course_Student` (
  `idStudent` INT NOT NULL,
  `idCourseCode` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idStudent`, `idCourseCode`),
  INDEX `fk_Student_has_Module_Module1_idx` (`idCourseCode` ASC) VISIBLE,
  INDEX `fk_Student_has_Module_Student1_idx` (`idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Module_Student1`
    FOREIGN KEY (`idStudent`)
    REFERENCES `CourseService`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Module_Module1`
    FOREIGN KEY (`idCourseCode`)
    REFERENCES `CourseService`.`Module` (`Course_idCourseCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`Module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`Module` (
  `idModuleCode` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Course_idCourseCode` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idModuleCode`, `Course_idCourseCode`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Module_Course1_idx` (`Course_idCourseCode` ASC) VISIBLE,
  CONSTRAINT `fk_Module_Course1`
    FOREIGN KEY (`Course_idCourseCode`)
    REFERENCES `CourseService`.`Course` (`idCourseCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`msgdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`msgdetail` (
  `msgdetailid` INT NOT NULL,
  `msgInboxId` INT NOT NULL,
  `msgInboxUid` INT NOT NULL,
  `msgFromUid` INT NOT NULL,
  `msgToUid` INT NOT NULL,
  `msgTimestamp` DATETIME NOT NULL,
  `msginbox_msginboxid` INT NOT NULL,
  PRIMARY KEY (`msgdetailid`),
  INDEX `fk_msgdetail_msginbox1_idx` (`msginbox_msginboxid` ASC) VISIBLE,
  CONSTRAINT `fk_msgdetail_msginbox1`
    FOREIGN KEY (`msginbox_msginboxid`)
    REFERENCES `CourseService`.`msginbox` (`msginboxid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`msginbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`msginbox` (
  `msginboxid` INT NOT NULL,
  `msgInboxUid` INT NOT NULL,
  `msgFromUid` INT NOT NULL,
  `msgToUid` INT NOT NULL,
  `msgLine` VARCHAR(1000) NOT NULL,
  `msgTimestamp` DATETIME NOT NULL,
  `msgProductId` INT NOT NULL,
  `user_userid` INT NOT NULL,
  PRIMARY KEY (`msginboxid`),
  INDEX `fk_msginbox_user1_idx` (`user_userid` ASC) VISIBLE,
  CONSTRAINT `fk_msginbox_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `CourseService`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`product` (
  `productid` INT NOT NULL AUTO_INCREMENT,
  `ownerid` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `imageUrl1` VARCHAR(200) NULL,
  `imageUrl2` VARCHAR(200) NULL,
  `imageUrl3` VARCHAR(200) NULL,
  `defaultPic` INT NULL,
  `price` DECIMAL(2) NOT NULL,
  `dateUpdated` DATETIME NOT NULL,
  `soldStatus` TINYINT NULL,
  `deleteStatus` TINYINT NULL,
  `user_userid` INT NOT NULL,
  PRIMARY KEY (`productid`, `user_userid`),
  INDEX `fk_product_user1_idx` (`user_userid` ASC) VISIBLE,
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `CourseService`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`Student` (
  `idStudent` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `birthDate` DATETIME NOT NULL,
  `nationality` INT NOT NULL,
  PRIMARY KEY (`idStudent`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Student_Country_idx` (`nationality` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Country`
    FOREIGN KEY (`nationality`)
    REFERENCES `CourseService`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `displayName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `pw` VARCHAR(45) NOT NULL,
  `userImgUrl` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseService`.`watchlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseService`.`watchlist` (
  `watchlistid` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `productid` INT NOT NULL,
  `dateUpdated` DATETIME NOT NULL,
  `deleteStatus` TINYINT NULL,
  `watchlist` VARCHAR(45) NULL,
  `user_userid` INT NOT NULL,
  `product_productid` INT NOT NULL,
  `product_user_userid` INT NOT NULL,
  PRIMARY KEY (`watchlistid`, `user_userid`, `product_productid`, `product_user_userid`),
  INDEX `fk_watchlist_user1_idx` (`user_userid` ASC) VISIBLE,
  INDEX `fk_watchlist_product1_idx` (`product_productid` ASC, `product_user_userid` ASC) VISIBLE,
  CONSTRAINT `fk_watchlist_user1`
    FOREIGN KEY (`user_userid`)
    REFERENCES `CourseService`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watchlist_product1`
    FOREIGN KEY (`product_productid` , `product_user_userid`)
    REFERENCES `CourseService`.`product` (`productid` , `user_userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
